### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KMCGamer** [SCCapstone/Cupboard#57]
**Home Screen (new Dashboard):**
- [x] Home no longer controls navigation
- [x] List of items close to expiration
- [ ] Recipe suggestion
- [ ] Foods you're running low on
- [x] Last shopping list you added

**Cupboard:**
- [x] CRUD for foods
- [x] Everything should automatically update from firebase (aka: editing firebase directly auto updates the app)
- [x] Add food to list button
- [x] Reorder list

**Shopping Lists:**
- [x] CRUD for lists
- [x] CRUD for list items
- [x] Reorder both lists and listitems 
- [ ] Everything should automatically update from firebase (aka: editing firebase directly auto updates the app)
- [ ] Implement parent lists + sublists
- [ ] Mark shopping list as complete (auto add to cupboard?)
